### PR TITLE
suggest new Test::Alien instead of Test::CChecker

### PR DESCRIPTION
**Pull request by plicease**
I would like to recommend `Test::Alien` instead of `Test::CChecker`.  I am the author of both, so if you have any questions about them please let me know.

I am also adding `Test::Alien` to the travis build as I am planning on adding `Test::Alien` tests to the Acme modules to see if I can flush out any issues with `Test::Alien`.

### CODE REVIEW

**Comment by mohawk2** [comment]
Sounds like a good idea. Soon as that Travis issue is sorted, aye :-)

**Comment by plicease** [comment]
The travis fix is already included in #139

**Comment by plicease** [comment]
sorry deleted this branch by mistake

**Comment by mohawk2** [comment]
Works for me. Aye!

**Comment by jberger** [comment]
If you believe that Test::Alien is ready for use, then a doc patch is fine by me: aye

**Pull request merged**
