### PR TITLE
fix A::B::PkgConfig::read

### PR DESCRIPTION
**Pull request by dakkar**
It got confused by lines contaninig both colons and equal signs. I've also updated the tests.

### CODE REVIEW

**Comment by plicease** [comment]
This looks correct to me, Aye.

**Comment by jberger** [comment]
I defer to @plicease on issues like this. Aye

**Comment by zmughal** [comment]
Looks good to me!

**Merge**: *Aye*

**Comment by plicease** [comment]
@dakkar++ for identifying the problem and providing a patch.

Released this as dev version `0.028_01`.  I expect if there are no show stoppers revealed by cpantesters that I will do a production release later this week.

**Pull request merged**
