### PR TITLE
create a config.site file for autoconf

### PR DESCRIPTION
**Pull request by plicease**
This creates a `config.site` file for autoconf so that it will make autoconf use the same compiler, compiler flags and linker flags as Perl.

This makes source code builds on Solaris with 64 bit Perls work.  (tested).  It stands a decent chance of also working on HP-UX and AIX with 64 bit Perls, since it relies on the Perl Config module.  (untested).

The problem with platforms like Solaris, HP-UX and AIX is that they are mixed 32/64 bit environments where 32 bit is usually they default.

Caveats:

  - I'm stripping out `-D` (Define) flags as they are Perl specific.
  - If `CONFIG_SITE` is already set, then we defer to that.  The assumption is that if integrators / users have set this variable they have set it for the correct compiler.

### CODE REVIEW

**Comment by plicease** [comment]
btw- I considered generating the `config.site` file when `Alien::Base` is installed, and putting it in a `share` directory for that, but I know that people do sometimes update `Config.pm`, and it may be useful to allow people do that so they can fix stuff.

**Comment by mohawk2** [comment]
Yes, I've locally changed my Config setup (specifically Config_heavy's "make" setting) to test different things, and would be unimpressed if a tool like A::B ignored that. Very good work! Aye.

**Comment by plicease** [comment]
Just a heads up, I plan on merging this and #112 on Friday and doing a dev release unless someone speaks up against against before then.

**Comment by zmughal** [comment]
+1

**Pull request merged**
