### PR TITLE
Fix Bug, Avoid Error "Use of uninitialized value $_ in delete at …

### PR DESCRIPTION
**Pull request by wbraswell**
…Alien/Base/ModuleBuild.pm line 740."

### CODE REVIEW

**Comment by wbraswell** [comment]
AppVeyor testing for Alien::Base is currently broken, so the "failure" of this pull request is not a real failure.

https://github.com/Perl5-Alien/Alien-Base/issues/174

**Comment by plicease** [comment]
This diagnostic is harmless (again, it hasn't been determined that this is a bug), but would prefer not to silence it until we can determine why there is an undef in `@PATH`.  This patch is also more complicated that it needs to be a simple grep removing undefined methods would be better.  In addition, I don't mind you pointing out errors and typos in the `Changes` file, but making alterations to the version number and bumping the `Changes` file is not appropriate, we have a procedure for this and it is handled during releases.  Therefore for the timing being I vote **ney**.

**Comment by wbraswell** [comment]
I solved the mystery of the undef in @PATH for Windows, but not for Solaris.
On Windows in AppVeyor, it was caused by a trailing semicolon on a set command for the path env var:

`set PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;C:\windows\system32;C:\windows;`

should have been:

`set PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;C:\windows\system32;C:\windows`

or more correctly:

`set PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;C:\windows\system32;C:\windows;%path%`

Of course this still doesn't answer why it was happening in Solaris on CPAN Testers.

If you consider this an actual "diagnostic" message, then sure, leave it in, I was lead to believe it was a bug which needed to be fixed.

**Comment by wbraswell** [comment]
If you want to use a "simple grep" or not remove the warning at all, that's your call, go ahead and close the PR if that is the case.

**Comment by wbraswell** [comment]
Fixed by 
https://github.com/Perl5-Alien/Alien-Base/pull/175

**Pull request closed without merging**
