### PR TITLE
./Build alien_dry_run

### PR DESCRIPTION
**Pull request by plicease**
Debugging a issue with `Alien::FFI` on MSWin32 and it was useful to be able to see the commands as they would actually be executed, without actually executing, so I added an ACTION_alien_dry_run.

Its not quite as clever as I would like it to be (ie, would be nice to probe the repositories and tell me exactly which one(s) it would download), but I think this is a good start.

### CODE REVIEW

**Comment by plicease** [comment]
rebased and updated to reflect that commands can be array refs.  

I recall now that there is a `./Build fakeinstall` command so maybe a more suitable name is `fakebuild` or `alien_fakebuild`?

**Comment by zmughal** [comment]
Merge: *Aye*.

I like the name `alien_fakebuild`, but I'm not the best person to comment on that. :-P

**Comment by plicease** [comment]
@zmughal that name is growing on me too, pending further input I will rename it before merging if this is approved.

**Comment by jberger** [comment]
I have often used dry_run in things, but yeah I think fakebuild is more consistent. Aye

**Comment by mohawk2** [comment]
I say whatever name is considered best. Otherwise, "aye".

**Comment by plicease** [comment]
Sent to CPAN as 0.009_01

**Pull request merged**
