### PR TITLE
documentation tweaks

### PR DESCRIPTION
**Pull request by plicease**
- update the copyright year range
- remove repeated AUTHOR section in one document
- list myself as an author in POD and dist meta.

Not trying to cut anyone out, and if anyone else wants to be added to the AUTHOR section I am happy to adjust this PR accordingly (everyone is already listed in the CONTRIBUTOR section already I believe).  It just seems to be sensible to have an active developer as an author contact in the dist meta and POD is a good idea.  Since I am doing the releases for now, I picked myself.

I think the other items should be non-controversial, but speak up if you have objections.

### CODE REVIEW

**Comment by mohawk2** [comment]
Looks fine to me. Why are META.{json,yml} under source control? Can't we delete them?

**Comment by plicease** [comment]
Just historical.

I think with a META.json you can do a `cpanm --installdeps .` to install deps, but this has never been a strong motivational reason for me in my dists.

**Comment by jberger** [comment]
Almost certainly that is historical. I used to do it. Then a few times I forgot to regenerate them and had PAUSE problems etc. Since then I don't keep the META or MANIFEST files in version control in my projects anymore. Guess I didn't do that here, but I recommend that we do.

**Comment by mohawk2** [comment]
I'd like to see it not be source-controlled if possible.

**Comment by jberger** [comment]
I'm ok with the changes, merge and remove the meta files from source control while you are at it :+1:

**Comment by zmughal** [comment]
Merge: *Aye* from me.

**Comment by plicease** [comment]
merged.

**Pull request closed without merging**
