### PR TITLE
Use the base_url from the request

### LINKED ISSUE #150: Download of JTPALMER/Alien-Chipmunk-0.001000.tar.gz broken with 0.025
See subject. If I use Alien-Base-0.024, then the download works again. I see some URI-related change in the CHANGES file --- maybe this is causing the problem?

@jtpalmer : FYI (because of the UNKNOWN reports which will appear @ cpantesters now).

### PR DESCRIPTION
**Pull request by plicease**
This fixes #150 

Briefly, the problem is that if you provide something like

 "/foo/bar"

as the location, and that location is a directory, then the remote server will redirect you to "/foo/bar/" before returning the directory listing.  LWP::UserAgent or HTTP::Tiny will do this for you, but if you use "/foo/bar" as the base_url then any relative URLs will be wrong.

Ideally AB modules should specify "/foo/bar/" but this is an easy fix for modules that do not.

### CODE REVIEW

**Comment by plicease** [comment]
/cc: @salva this is related to #144 

I tested a number of dists before applying that PR, but obviously all of them had the trailing / in the location field.

**Comment by zmughal** [comment]
This seems reasonable to me. And if it works with Alien-Chipmunk as mentioned in #150, I think that's good enough of a test.

**Merge**: *Aye*

**Comment by plicease** [comment]
Yup.  It fixes Alien::Chipmunk, I even tested with protocol_class=LWP::UserAgent

**Comment by jberger** [comment]
certainly it shouldn't matter if someone appends a trailing slash, aye!

**Comment by plicease** [comment]
Testing with some other distros (with and without the /) and will do a production release shortly.

**Pull request merged**
