### PR TITLE
Allow overriding repo config from ENV

### PR DESCRIPTION
**Pull request by nshp**
Allows e.g.:

    ALIEN_OPENSSL_REPO_FTP_HOST=example.com cpanm Alien::OpenSSL

### CODE REVIEW

**Comment by wbraswell** [comment]
Seems legit?

**Comment by plicease** [comment]
Going to do some testing, but I think I largely approve.  I appreciate the documentation on the environment variables, which are also buried in the documentation here:

https://metacpan.org/pod/distribution/Alien-Base/lib/Alien/Base/ModuleBuild/API.pod#PACKAGE-AND-ENVIRONMENT-VARIABLES

**Comment by plicease** [comment]
I did some testing with my own `Alien::FFI`, and I vote for inclusion.  I will merge this Thursday if there aren't any objections before then.

**Comment by plicease** [comment]
Rebased and merged.  I am going to send this to CPAN now.

**Pull request closed without merging**
